#!/usr/bin/env bash
# redirection must be a "301 Moved Permanently"
sudo apt-get update;
sudo apt-get install -y nginx;
sudo sed -i '26i\    	rewrite ^/redirect_me https://isitchristmas.com/ permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start;
