#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but says hi if 9
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    ((i++))
    if [ $i -eq 9 ]
    then
	echo "Holberton School"
	echo "Hi"
	((i++))
    fi
done
