#!/usr/bin/env bash
# This script will print out 'Holberton School' 20 times with other insertions
i=1
while ((i < 21))
do
    echo "$i"
    ((i++))
    case $i in
	5)
	    echo "bad luck from china";;
	10)
	    echo "bad luck from Japan";;
	18)
	    echo "bad luck from Italy";;
    esac
done
