#!/usr/bin/env bash
# This script will tell you the time for a 12 hour clock
hour=0
while ((hour < 13))
do
echo "Hour: $hour"
min=1
while ((min < 60))
do
    echo "$min"
    ((min++))
done
((hour++))
done
