#!/usr/bin/env bash
# Bash script to turn on firewall so it blocks all incoming traffic
# except port 22 443 and 80
sudo ufw allow 22/tcp
sudo ufw allow 443
sudo ufw allow 80
sudo ufw default deny incoming
sudo ufw enable
